# Generated by Django 4.1.13 on 2024-02-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="collect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="funds.collect",
                verbose_name="Сбор",
            ),
        ),
    ]
